name: Lint, Type Check, Test, and Build

on:
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node24-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node24-

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run integration tests (Vitest)
        run: npm run test

      - name: Build project
        run: npm run build
